language: python
python:
  - 3.8.1
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key: 8626f6d1-9d91-4a68-be0e-c1b4b1700f1a
  app: APP
  run: python manage.py migrate
  on: master
