# Generated by Django 3.0.2 on 2020-02-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0002_auto_20200205_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_category', models.CharField(choices=[('matric', 'Matric'), ('inter', 'Inter'), ('graduation', 'Graduation'), ('post_graduation', 'Post-Graduation')], default='inter', max_length=25)),
                ('post_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('admit_card', 'Admit Card'), ('result', 'Result'), ('entries', 'Entries')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='job_openings.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='job_openings.SubCategory'),
        ),
    ]
