# Generated by Django 3.0.2 on 2020-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0003_auto_20200208_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ManyToManyField(blank=True, related_name='links', to='job_openings.Post')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
