# Generated by Django 3.0.2 on 2020-02-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0004_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
