# Generated by Django 3.0.2 on 2020-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0005_auto_20200208_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
