# Generated by Django 3.0.2 on 2020-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0009_auto_20200209_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='choices',
            field=models.CharField(choices=[('form', 'Form'), ('admitCard', 'Admit-Card'), ('result', 'Result')], default='form', max_length=20),
        ),
    ]
