# Generated by Django 3.0.2 on 2020-02-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0010_formtype_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='form_type',
        ),
        migrations.DeleteModel(
            name='FormType',
        ),
    ]
